### ISSUE TITLE
No text shown in translate dialog

### ISSUE THREAD

**Issue by sankaritan** [kitt-browser/translate#17]
How to reproduce:
- Install latest version of translate into Kitt 1.3.5
- Open some website not in english. Tested with article from idnes.cz or canadiens.nhl.com (french version)
- select some text and press Translate
- translate dialog is shown but it is empty - only dropdown with "autodetect" is shown, no translated message. Also related to https://github.com/kitt-browser/translate/issues/18

![file jul 27 1 33 44 pm](https://cloud.githubusercontent.com/assets/6403413/8904971/3062361c-3464-11e5-813f-7d4e35f011d9.png)

**Comment by dedecej** [comment]
Fixed
